pool:
  vmImage: 'ubuntu-20.04'
trigger:
  - master
variables:
  - group: ServicePrincipal-kredki
steps:                 
      - task: AzureCLI@2
        displayName: "Right Principal"
        inputs:
          azureSubscription: very_interesting_not_suspicious_connection
          scriptType: bash
          addSpnToEnvironment: true
          scriptLocation: inlineScript
          inlineScript: |
            az account set --subscription $(ARM-SUBSCRIPTION-ID)
            az login --service-principal -u $(ARM-CLIENT-ID) -p $(ARM-CLIENT-SECRET) --tenant $(ARM-TENANT-ID)